version: '3'
services:
  classyfire-web:
    build: .
    container_name: classyfireproxy
    ports:
    - "5057:5000"
    command: /app/run_server.sh
    depends_on: 
      - classyfire-redis
      - classyfire-mqrabbit
    networks:
      - default
    volumes:
    - ../cache:/data
    restart: unless-stopped
  classyfire-worker1:
    build: .
    container_name: classyfireproxy_worker1
    command: /app/run_celery_worker.sh
    restart: unless-stopped
    depends_on: 
      - classyfire-redis
      - classyfire-mqrabbit
    networks:
      - default
  classyfire-redis:
    image: redis
    container_name: classyfireproxy_redis
    networks:
      - default
    volumes:
    - ../cache:/data
    command: ["redis-server", "--appendonly", "yes"]
  classyfire-mqrabbit:
    image: rabbitmq:latest
    container_name: classyfireproxy_mqrabbit
    networks:
      - default
    


