version: '3'
services:
  web:
    build: .
    container_name: classyfireproxy
    ports:
    - "5057:5000"
    command: /app/run_server.sh
    depends_on: 
      - redis
    networks:
      - default
    restart: unless-stopped
  worker1:
    build: .
    container_name: classyfireproxy_worker1
    command: /app/run_celery_worker.sh
    restart: unless-stopped
    depends_on: 
      - redis
    networks:
      - default
  redis:
    image: redis
    networks:
      - default
    volumes:
    - ../cache:/data
    command: ["redis-server", "--appendonly", "yes"]
